# Generated by Django 2.1.4 on 2019-02-09 21:55

from django.db import migrations, models
import django.db.models.deletion
import linktosite.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('slug', models.SlugField(blank=True)),
                ('link', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=linktosite.models.image_folder)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linktosite.Category')),
            ],
        ),
    ]
