# Generated by Django 2.1.4 on 2019-02-13 21:33

from django.db import migrations, models
import linktosite.models


class Migration(migrations.Migration):

    dependencies = [
        ('linktosite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='image',
            field=models.ImageField(blank=True, upload_to=linktosite.models.image_folder),
        ),
    ]
