# Generated by Django 3.0.6 on 2020-07-03 21:17

from django.db import migrations, models
import linktosite.models


class Migration(migrations.Migration):

    dependencies = [
        ('linktosite', '0004_auto_20200701_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnauthorizedUserLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='Name')),
                ('slug', models.SlugField(blank=True)),
                ('link', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to=linktosite.models.image_folder, verbose_name='Image url')),
            ],
            options={
                'verbose_name': 'UnauthorizedUserLink',
                'verbose_name_plural': 'UnauthorizedUserLinks',
            },
        ),
    ]
