# Generated by Django 3.0.6 on 2020-07-16 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linktosite', '0005_unauthorizeduserlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Версия')),
                ('description', models.TextField(verbose_name='Что нового в версии')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Текущий год')),
            ],
        ),
    ]
