# Generated by Django 3.0.6 on 2020-07-16 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linktosite', '0008_auto_20200716_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='version',
            field=models.FloatField(verbose_name='Версия'),
        ),
    ]
